# Generated by Django 3.0.6 on 2020-12-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topimage',
            name='good',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
