# Generated by Django 3.0.6 on 2020-12-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_topimage_good'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topimage',
            name='good',
            field=models.IntegerField(default=0),
        ),
    ]
