# Generated by Django 3.0.6 on 2020-12-10 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='auther',
            field=models.CharField(max_length=100),
        ),
    ]
