# Generated by Django 3.0.6 on 2020-12-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201211_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='pablish',
            field=models.BooleanField(default=False),
        ),
    ]
