# Generated by Django 3.0.6 on 2020-12-12 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogmodel_pablish'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockExist',
            fields=[
                ('stock_id', models.IntegerField(primary_key=True, serialize=False)),
                ('stock_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_data', models.CharField(max_length=50)),
                ('open_data', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close_data', models.FloatField()),
                ('volume', models.IntegerField()),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.StockExist')),
            ],
        ),
    ]
